const fs = require('fs');
const path = require('path');

function humanSize(bytes) {
  if (bytes < 1024) return bytes + ' B';
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
  return (bytes / (1024 * 1024)).toFixed(2) + ' MB';
}

function readDirRecursive(dir, base) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const items = [];
  for (const e of entries) {
    const full = path.join(dir, e.name);
    const rel = path.relative(base, full).replace(/\\\\/g, '/');
    if (e.isDirectory()) {
      items.push({ type: 'dir', name: e.name, path: rel, children: readDirRecursive(full, base) });
    } else {
      const stat = fs.statSync(full);
      items.push({ type: 'file', name: e.name, path: rel, size: stat.size });
    }
  }
  return items;
}

function pickSizeStr(item) {
  if (item.type === 'file') return humanSize(item.size || 0);
  return '';
}

function buildMermaid(items) {
  // We'll focus on known groups and files for clarity, fall back to listing
  const nodes = [];
  const links = [];

  // helper to add node
  function addNode(id, label, cls) {
    nodes.push({ id, label, cls });
  }
  // Known important files
  const important = [
    'index.html', 'package.json', 'manifest.webmanifest', 'sw.js',
    'app.jsx', 'tweaks-panel.jsx', 'ios-frame.jsx'
  ];

  // Search for components/, data/, styles/, vendor/, icons/, uploads/
  const projectRoot = items;
  // Create root groups
  addNode('index', `index.html\\n(${findSize(projectRoot, 'index.html')})\\nentrada + sw register`, 'root');
  addNode('pkg', `package.json\\n(${findSize(projectRoot, 'package.json')})\\nscript: npm start`, 'root');
  addNode('manifest', `manifest.webmanifest\\n(${findSize(projectRoot, 'manifest.webmanifest')})\\nPWA metadata`, 'root');
  addNode('sw', `sw.js\\n(${findSize(projectRoot, 'sw.js')})\\nservice worker (cache)`, 'root');
  addNode('vendor', `vendor/\\n(${folderSize(projectRoot, 'vendor')})\\nllibreries locals`, 'root');
  addNode('styles', `styles/\\n(${folderSize(projectRoot, 'styles')})\\nestils globals`, 'root');
  addNode('icons', `icons/\\n(${folderSize(projectRoot, 'icons')})\\nicones PWA`, 'root');

  addNode('app', `app.jsx\\n(${findSize(projectRoot, 'app.jsx')})\\npunt d'inici`, 'central');

  // Components
  const compDir = findDir(projectRoot, 'components');
  if (compDir) {
    const comps = compDir.children.filter(c => c.type === 'file');
    comps.forEach(c => {
      const id = safeId(c.name);
      addNode(id, `${c.name}\\n(${humanSize(c.size)})`, 'comp');
      links.push({ from: 'app', to: id, label: 'carrega' });
    });
  }

  // Data
  const dataDir = findDir(projectRoot, 'data');
  if (dataDir) {
    const datas = dataDir.children.filter(c => c.type === 'file');
    datas.forEach(c => {
      const id = safeId(c.name);
      addNode(id, `${c.name}\\n(${humanSize(c.size)})`, 'data');
      // connect likely targets
      links.push({ from: 'app', to: id, label: 'usa' });
    });
  }

  // Specific connections (best-effort)
  links.push({ from: 'index', to: 'vendor', label: 'carrega' });
  links.push({ from: 'index', to: 'app', label: 'carrega' });
  links.push({ from: 'index', to: 'sw', label: 'registra' });
  links.push({ from: 'index', to: 'manifest', label: 'usa' });
  links.push({ from: 'index', to: 'styles', label: 'aplica estils' });

  // Service worker cache links
  links.push({ from: 'sw', to: 'index', label: 'cacha' });
  links.push({ from: 'sw', to: 'vendor', label: 'cacha' });
  links.push({ from: 'sw', to: 'styles', label: 'cacha' });
  links.push({ from: 'sw', to: 'icons', label: 'cacha' });

  // Vendor relations
  links.push({ from: 'vendor', to: 'app', label: "Babel runtime" });

  // build mermaid text
  let out = 'graph LR\\n';
  out += '  %% Auto-generated by scripts/generate-map.js\\n';

  nodes.forEach(n => {
    out += `  ${n.id}["${n.label}"]\\n`;
  });
  out += '\\n';
  links.forEach(l => {
    out += `  ${l.from} -- "${l.label}" --> ${l.to}\\n`;
  });

  // classes
  out += '\\n  class index,pkg,manifest,sw,vendor,styles,icons root;\\n';
  out += '  class app central;\\n';
  out += '  classDef root fill:#FFB300,stroke:#E65100,stroke-width:2px,color:#3E2723,font-size:12px;\\n';
  out += '  classDef central fill:#FFCC80,stroke:#FF6F00,stroke-width:2px,color:#3E2723,font-size:13px;\\n';
  out += '  classDef comp fill:#A5D6A7,stroke:#2E7D32,stroke-width:2px,color:#003300,font-size:12px;\\n';
  out += '  classDef data fill:#90CAF9,stroke:#0D47A1,stroke-width:2px,color:#002366,font-size:12px;\\n';
  out += '  classDef storage fill:#FFF59D,stroke:#F57F17,stroke-width:2px,color:#3E2723,font-size:12px;\\n';

  return out;
}

function findDir(list, name) {
  for (const it of list) {
    if (it.type === 'dir' && it.name === name) return it;
  }
  return null;
}

function findSize(list, filename) {
  for (const it of list) {
    if (it.type === 'file' && it.name === filename) return humanSize(it.size);
  }
  return '—';
}

function folderSize(list, dirname) {
  const dir = findDir(list, dirname);
  if (!dir) return '—';
  let total = 0;
  function walk(d) {
    for (const c of d.children) {
      if (c.type === 'file') total += c.size || 0;
      else walk(c);
    }
  }
  walk(dir);
  return humanSize(total);
}

function safeId(name) {
  return name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^[0-9]/, 'n$&');
}

// Run
const base = process.cwd();
const tree = readDirRecursive(base, base);
const mermaid = buildMermaid(tree);

fs.writeFileSync(path.join(base, 'ELBOSC-MAP.mmd'), mermaid);
const md = `# El Bosc · Mapa conceptual (auto-generat)\n\n\n\
\
\
\
\
\
\
\n\n\
\
\
\n\n";

// Also write a markdown wrapper containing the mermaid block
const mdContent = `# El Bosc · Mapa conceptual (auto-generat)\n\nObre aquest fitxer amb un visor Mermaid o genera les imatges amb la CLI.\n\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\n\n";

// Write a proper markdown file with fenced mermaid block
const mmdBlock = '```mermaid\n' + mermaid + '\n```\n';
fs.writeFileSync(path.join(base, 'ELBOSC-MAP.md'), '# El Bosc · Mapa conceptual (auto-generat)\n\n' + 'Aquest fitxer és generat automàticament.\n\n' + mmdBlock);
console.log('Wrote ELBOSC-MAP.mmd and ELBOSC-MAP.md');
